# all notebooks in this directory are synced percent format when typing
# (jupytext is a dev dependency)
# jupytext --sync *.ipynb
# or from root directory
# jupytext --sync notebooks/*.ipynb
formats = "ipynb,py:percent"